---
# handlers file for roles/prometheus
- name: restart_prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: yes
      #- name: reload_prometheus
      #  uri:
      # url: http://13.233.88.207:9090/-/reload
      # method: POST
      # status_code: 200
